/**
 * @file pager.cpp
 * @brief Memory Management Unit (MMU) & Paging system implementation.
 *
 * CONCEPTS IMPLEMENTED:
 *   1. Non-contiguous Allocation: Divides physical memory into fixed-size Frames.
 *   2. Logical-to-Physical Address Translation:
 *        Page Number  = LogicalAddress / PageSize
 *        Offset       = LogicalAddress % PageSize
 *        PhysicalAddr = (FrameNumber * PageSize) + Offset
 *   3. Page Fault Handling: Loads unmapped/faulted pages into free physical frames.
 *   4. Process Lifecycle: Loads process pages into free frames or deallocates on completion.
 */

#include "memory_manager/paging/pager.h"

/**
 * @brief Initializes physical RAM into fixed-size frames.
 * @param numberOfFrames Total physical frames in system.
 * @param pageSize Size of each frame/page in KB/bytes.
 */
Pager::Pager(int numberOfFrames, int pageSize)
    : pageSize(pageSize)
{
    for (int i = 0; i < numberOfFrames; i++)
    {
        frames.emplace_back(i);
    }
}

/**
 * @brief Helper function to find the first unallocated physical frame.
 * @return Pointer to free Frame, or nullptr if physical RAM is full.
 */
Frame *Pager::findFreeFrame()
{
    for (Frame &frame : frames)
    {
        if (frame.isFree())
        {
            return &frame;
        }
    }
    return nullptr;
}

/**
 * @brief Loads a process into physical RAM by assigning free frames to its pages.
 *
 * @param process Process requesting memory allocation.
 * @return true if process successfully loaded, false if insufficient frames (with rollback).
 */
bool Pager::loadProcess(const Process &process)
{
    int pid = process.getPid();

    // Already loaded? Return false
    if (pageTables.find(pid) != pageTables.end())
    {
        return false;
    }

    // Calculate pages required (ceil division)
    int pagesNeeded = (process.getMemorySize() + pageSize - 1) / pageSize;
    PageTable pageTable(pid);
    std::vector<Frame *> allocatedFrames;

    for (int pageNumber = 0; pageNumber < pagesNeeded; pageNumber++)
    {
        Frame *frame = findFreeFrame();

        // Rollback allocation if RAM runs out mid-process allocation
        if (frame == nullptr)
        {
            for (Frame *allocated : allocatedFrames)
            {
                allocated->clear();
            }
            return false;
        }

        // Map frame to process page
        frame->setFree(false);
        frame->setPid(pid);
        frame->setPageNumber(pageNumber);
        allocatedFrames.push_back(frame);

        Page page(pid, pageNumber);
        page.setLoaded(true);
        page.setFrameNumber(frame->getFrameNumber());
        pageTable.addPage(page);
    }

    pageTables[pid] = pageTable;
    return true;
}

/**
 * @brief Deallocates all frames owned by PID and removes its page table entry.
 */
bool Pager::deallocateProcess(int pid)
{
    auto it = pageTables.find(pid);
    if (it == pageTables.end())
    {
        return false;
    }

    for (Frame &frame : frames)
    {
        if (frame.getPid() == pid)
        {
            frame.clear();
        }
    }

    pageTables.erase(it);
    return true;
}

const std::vector<Frame> &Pager::getFrames() const { return frames; }
const std::unordered_map<int, PageTable> &Pager::getPageTables() const { return pageTables; }

/**
 * @brief MMU Address Translation Engine.
 *
 * Translates a process Logical Address into a Physical RAM Address:
 *   Logical Address -> (Page Number, Offset) -> Page Table Lookup -> (Frame Number, Offset) -> Physical Address
 *
 * @param pid Process ID making memory access.
 * @param logicalAddress Logical address generated by CPU.
 * @return Physical address, or -1 if invalid address/page fault fails.
 */
int Pager::translateAddress(int pid, int logicalAddress)
{
    auto process = pageTables.find(pid);
    if (process == pageTables.end())
    {
        return -1; // Process page table not found
    }

    PageTable &pageTable = process->second;

    int pageNumber = logicalAddress / pageSize;
    int offset = logicalAddress % pageSize;

    if (pageNumber >= pageTable.getPages().size())
    {
        return -1; // Segmentation Fault: Address out of bounds
    }

    const Page &page = pageTable.getPage(pageNumber);

    // Page Fault handling if page is not loaded in RAM
    if (!page.isLoaded())
    {
        if (!handlePageFault(pid, pageNumber))
        {
            return -1; // Page fault resolution failed (RAM full)
        }
    }

    int frameNumber = page.getFrameNumber();

    // Physical Address = (Frame Number * Page Size) + Offset
    return frameNumber * pageSize + offset;
}

/**
 * @brief Page Fault Handler.
 *
 * Fetches an unmapped page into a free frame in physical RAM.
 */
bool Pager::handlePageFault(int pid, int pageNumber)
{
    auto process = pageTables.find(pid);
    if (process == pageTables.end())
    {
        return false;
    }

    PageTable &table = process->second;
    Page &page = table.getPage(pageNumber);

    if (page.isLoaded())
    {
        return true;
    }

    Frame *frame = findFreeFrame();
    if (frame == nullptr)
    {
        return false; // Out of memory
    }

    frame->setFree(false);
    frame->setPid(pid);
    frame->setPageNumber(pageNumber);

    page.setFrameNumber(frame->getFrameNumber());
    page.setLoaded(true);

    return true;
}